# Collabrative Filtering data set taken from Collective Intelligence book.


dataset ={
			'Hung': {'Iron Man': 2.5,
							'Spiderman': 3.5,
							'Venom': 3.0,
							'Superman Returns': 3.5, 
							'Bat Man': 2.5,
							'Deadpool': 3.0,
					 		'The gioi khung long':5.0,
					 },
			'Dong': {'Iron Man': 3.0,
							'Spiderman': 3.5,
							'Venom': 1.5,
							 'Superman Returns': 5.0, 
							 'Deadpool': 3.0,
							'Bat Man': 3.5},

			'Tai': {'Iron Man': 2.5,
								'Spiderman': 3.0,
								'Superman Returns': 3.5,
								 'Deadpool': 4.0,
								'dau pha thuong khung':1.0,
					},
			'Nhung': {'Spiderman': 3.5,
							'Venom': 3.0,
							'Deadpool': 4.5,
							'Superman Returns': 4.0,
							'Bat Man': 2.5},
			'Nam': {'Iron Man': 3.0,
							'Spiderman': 4.0,
							'Venom': 2.0,
							'Superman Returns': 3.0, 
							'Deadpool': 3.0,
							'Bat Man': 2.0},
			'Jack': {'Iron Man': 3.0,
							'Spiderman': 4.0,
							'Deadpool': 3.0,
							'Superman Returns': 5.0, 
							'Bat Man': 3.5},
			'Toby': {'Spiderman':4.5,
					'Bat Man':1.0,
					'Superman Returns':4.0},
			'Hai':{'Venom': 5.0,
					'Bat Man': 3.0,
					'Superman Returns': 4.5},
			'khiet':{
				'Iron Man': 5.0,
				'Venom': 3.0,
			}
}